events {}

http {
    server {
        listen 80;
        server_name _;

        location / {
            root /var/www/output;
            autoindex on;
            try_files $uri $uri/ =404;
        }
    }
}
